require "user.core.plugins"
require "user.core.telescope"
require "user.core.toggleterm"
require "user.core.whichkey"
require "user.core.bufferline"
require "user.core.nvim-tree"
require "user.core.lualine"
